/*
=!EXPECTSTART!=
[ "AA", "CC.txt" ]
XX1
XX1/CC
CC.txt
directory
.txt
true
true
true
true
false
=!EXPECTEND!=
*/
file.mkdir('XX1');
file.mkdir('XX1/AA');
file.mkdir('XX1/BB');
file.rename('XX1/BB','XX1/CC.txt');
puts(file.glob(null,'XX1').sort());
puts(file.dirname('XX1/AA'));
puts(file.rootname('XX1/CC.txt'));
puts(file.tail('XX1/CC.txt'));
puts(file.type('XX1/CC.txt'));
puts(file.extension('XX1/CC.txt'));
//puts(file.realpath('XX1/CC.txt'));
puts(file.writable('XX1/CC.txt'));
puts(file.readable('XX1/CC.txt'));
puts(file.exists('XX1/CC.txt'));
puts(file.isdir('XX1/CC.txt'));
puts(file.isfile('XX1/CC.txt'));
file.remove('XX1',true);
